name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.62.2
          cache: true

      - name: Install dependencies
        run: pixi install

      - name: Code check
        run: pixi run ruff check .

      - name: Run tests
        run: pixi run -e test-env test